version: '3.9'
services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - ./docker/config.env
    networks:
      - app-net

  db:
    image: mariadb:10.7.3
    restart: unless-stopped
    volumes:
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=djangodb
      - MYSQL_USER=django
      - MYSQL_PASSWORD=secret
      - TZ=Asia/Bangkok
    command: ['mysqld', '--default-time-zone=+07:00']
    ports:
      - 3306:3306
    networks:
      - app-net

  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 8080:8080
    networks:
      - app-net

networks:
  app-net:
